version: '3'

services:
  oracle-server:
    image: bitcoinscala/bitcoin-s-oracle-server:latest
    container_name: oracle-server
    restart: always
    volumes:
      - ${PWD}/oracle-server-data:/home/bitcoin-s/.bitcoin-s
    ports:
      - 9998:9998
    expose:
      - 9998
    networks:
      - dlc-oracle-bot-network

  announcer:
    build: dlc_oracle_bot
    container_name: announcer
    restart: always
    entrypoint: ["/announcer.sh"]
    volumes:
      - ${PWD}/dlc_oracle_bot:/usr/src/dlc_oracle_bot
    environment:
      CRYPTOWATCH_PUBLIC_KEY: "${CRYPTOWATCH_PUBLIC_KEY}"
    depends_on:
      - oracle-server
    networks:
      - dlc-oracle-bot-network

networks:
  dlc-oracle-bot-network:
    driver: bridge